sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull ijun/wndr4300-lede-sdk

script:
  - docker run -t -v "$TRAVIS_BUILD_DIR:/home/mockbuilder/sdk/package/custom" -i ijun/wndr4300-lede-sdk sudo -iu mockbuilder sh package.sh
